# Site settings
title: "(Infocrea Oy) -> Jarmo Lahti"
description: "infocrea.fi -> jarmolahti.fi"
baseurl: ""
url: "https://infocrea.jarmolahti.fi"
email: ""

# Build settings
markdown: kramdown
permalink: /blogi/:year/:month/:title/
paginate: 15
plugins: [jekyll-paginate]
paginate_path: '/blogi/:num/'
highlighter: pygments
excerpt_separator: <!--more-->
