# Site settings
title: "Infocrea Oy"
description: "Infocrea Oy - Information w. Creativity  | Luovaa tiedonjalostusta"
baseurl: ""
url: "http://www.infocrea.fi"
email: "jarmo.lahti@infocrea.fi"

# Build settings
markdown: kramdown
permalink: /blogi/:year/:month/:title/
paginate: 10
paginate_path: '/blogi/page/:num/'
highlighter: pygments
excerpt_separator: <!--more-->