# Site settings
title: "Infocrea Oy"
description: "Infocrea Oy - Information w. Creativity | Luovaa tiedonjalostusta"
baseurl: ""
url: "https://www.infocrea.fi"
email: "jarmo.lahti@infocrea.fi"

# Build settings
markdown: kramdown
permalink: /blogi/:year/:month/:title/
paginate: 15
plugins: [jekyll-paginate]
paginate_path: '/blogi/:num/'
highlighter: pygments
excerpt_separator: <!--more-->
